/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.kutuphane.mavenproject1;

import java.io.File;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vektorel
 */
public class FrmKutuphane extends javax.swing.JFrame {

    public static List<Kitaplar> kitapListe = new ArrayList<Kitaplar>();

    /**
     * Creates new form FrmKutuphane
     */
    public FrmKutuphane() {
        initComponents();
        tabloDoldurucu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablo = new javax.swing.JTable();
        btnKitapEkle = new javax.swing.JButton();
        btnOdunc = new javax.swing.JButton();
        btnIade = new javax.swing.JButton();
        btnCıkar = new javax.swing.JButton();
        btnDegistir = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTablo);

        btnKitapEkle.setText("Kitap Ekle");
        btnKitapEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKitapEkleActionPerformed(evt);
            }
        });

        btnOdunc.setText("Ödünç");
        btnOdunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOduncActionPerformed(evt);
            }
        });

        btnIade.setText("Geri Geldi");
        btnIade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIadeActionPerformed(evt);
            }
        });

        btnCıkar.setText("Kitap Çıkar ");
        btnCıkar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCıkarActionPerformed(evt);
            }
        });

        btnDegistir.setText("Kitap Değiştir");
        btnDegistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDegistirActionPerformed(evt);
            }
        });

        btnExcel.setText("Excele Aktar");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        jMenu1.setText("Kütüpist");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOdunc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKitapEkle, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addComponent(btnIade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDegistir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCıkar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnKitapEkle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOdunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCıkar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDegistir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExcel)
                .addGap(0, 111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKitapEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKitapEkleActionPerformed
        KitapEkle kEkle = new KitapEkle(this, true);
        kEkle.show();
        tabloDoldurucu();
    }//GEN-LAST:event_btnKitapEkleActionPerformed

    private void btnOduncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOduncActionPerformed
        int selectedRow = tblTablo.getSelectedRow();
        if (selectedRow != -1) {
            DlgOdunc odunc = new DlgOdunc(this, true, selectedRow);
            odunc.show();
            tabloDoldurucu();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Satır seçiniz");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnOduncActionPerformed

    private void btnIadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIadeActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblTablo.getSelectedRow();
        if (selectedRow != -1) {
            Kitaplar kOd= new Kitaplar();
            
 FrmKutuphane.kitapListe.get(selectedRow).setKimde(null);

            tabloDoldurucu();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Satır seçiniz");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIadeActionPerformed

    private void btnCıkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCıkarActionPerformed
  int selectedRow = tblTablo.getSelectedRow();
        if (selectedRow != -1) {
 kitapListe.remove(selectedRow);                            

            tabloDoldurucu();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Satır seçiniz");
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCıkarActionPerformed

    private void btnDegistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDegistirActionPerformed
   int selectedRow = tblTablo.getSelectedRow();
        if (selectedRow != -1) {
            DlgDegistir degistir= new DlgDegistir(this, true, selectedRow);
           degistir.show();
            tabloDoldurucu();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Satır seçiniz");
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnDegistirActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
 try
 {
 ExlUtil excelbas = new ExlUtil(); // Class'în bir nesnesini oluşturduk
 excelbas.fillData(tblTablo, new File("C:\\Intel\\tablo.xls")); // hangi tabloyu basacağımızı ve yolu belirledik.
 JOptionPane.showMessageDialog(null, "Dosya " + "'D: \\ tablo.xls' adresine başarıyla kaydedildi",//Başarılı Mesajı
 "Tablo Oluşturuldu", JOptionPane.INFORMATION_MESSAGE);
 }
 catch (Exception ex)
 {
 ex.printStackTrace();
 }       // TODO add your handling code here:
    }//GEN-LAST:event_btnExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmKutuphane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmKutuphane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmKutuphane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmKutuphane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmKutuphane().setVisible(true);
            }
        });
    }

    public void tabloDoldurucu() {

        String[] baslik = new String[]{"Kitap", "Yazar", "Yer", "Kimde"};
        String[][] doldur = new String[kitapListe.size()][4];

        for (int i = 0; i < kitapListe.size(); i++) {
            doldur[i][0] = kitapListe.get(i).getAd();
            doldur[i][1] = kitapListe.get(i).getYazar();
            doldur[i][2] = kitapListe.get(i).getYer();
            doldur[i][3] = kitapListe.get(i).getKimde();

        }
        tblTablo.setModel(new DefaultTableModel(doldur, baslik));


    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCıkar;
    private javax.swing.JButton btnDegistir;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnIade;
    private javax.swing.JButton btnKitapEkle;
    private javax.swing.JButton btnOdunc;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTablo;
    // End of variables declaration//GEN-END:variables
}
